### ISSUE TITLE
Publish Github Pages

### ISSUE THREAD

**Issue by Scrxtchy** [tz-dev/hl_text2speech#1]
Having a github page for the repository allows github to host it from their own infrastructure with content from the repository, this will make it a lot easier to demo,

link to content can be placed into the readme

**Comment by tz-dev** [comment]
hi! 

thanks a lot for the tip, i came back to the hub after a break.

it's a very nice feature, yet when i publish the site, i do not get forwarded to the index.html

so it's just https://tz-dev.github.io/hl_text2speech/
instead of https://tz-dev.github.io/hl_text2speech/index.html

was this what you meant by "link to content"?

**Comment by Scrxtchy** [comment]
It appears to be working for me
![image](https://user-images.githubusercontent.com/12771982/61581655-86e8e500-ab64-11e9-8093-69b67ddff9d3.png)

**Comment by tz-dev** [comment]
hm, strange. now it works for me, too. and i got what you meant by linking to it in the readme, thanks!
